import React from 'react'

const AugmentedGAN = () => {
  return (
    <div>
        <p>This page shows how a country would look like in the future.</p>
        <p>The photos are generated by an AI using Generative Adverserial Networks showing the future view of each place in a particular country in the future</p>
    </div>
  )
}

export default AugmentedGAN